auths/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/urls.py
# Copyright 2018 win10-pc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'blog'  # namespace
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='blog/login.html'),
        name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='blog/logout.html'),
        name='logout'),
    path('index/', views.BlogIndex.as_view(), name='index'),
    path('list/', views.BlogList.as_view(), name='list'),
    path('detail/<int:pk>/', views.BlogDetail.as_view(), name='detail'),
    path('publish/', views.BlogPublish.as_view(), name='publish'),
]

blog/models.py
# Blog (c) by yanjl
#
# Blog is licensed under a
# Creative Commons Attribution 3.0 Unported License.
#
# You should have received a copy of the license along with this
# work.  If not, see <http://creativecommons.org/licenses/by/3.0/>.

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=300, verbose_name='标题')
    body = models.TextField(verbose_name='内容')
    publish = models.DateTimeField(default=timezone.now, verbose_name='发布日期')
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='所有者')

    class Meta:
        ordering = ['-publish']
        verbose_name = '帖子'
        verbose_name_plural = '帖子'

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Blog


class RegisterModelForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'owner']
        labels = {
            'title': '标题',
            'body': '内容',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'owner': forms.HiddenInput(),
        }

blog/views.py
# Blog (c) by win10-pc
#
# Blog is licensed under a
# Creative Commons Attribution 3.0 Unported License.
#
# You should have received a copy of the license along with this
# work.  If not, see <http://creativecommons.org/licenses/by/3.0/>.

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from .forms import RegisterModelForm
from .models import Blog


class BlogIndex(TemplateView):
    template_name = 'blog/index.html'


class BlogList(LoginRequiredMixin, ListView):
    model = Blog
    context_object_name = 'posts'
    template_name = 'blog/list.html'
    paginate_by = 3

    def get_queryset(self):
        return Blog.objects.all().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = self.get_queryset().count

        return context


class BlogOwnerMixin:
    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        pk = self.kwargs.get(self.pk_url_kwarg, None)
        queryset = queryset.filter(
            pk=pk,
            owner=self.request.user,
        )

        try:
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise PermissionDenied

        return obj


class BlogDetail(LoginRequiredMixin, BlogOwnerMixin, DetailView):
    model = Blog
    context_object_name = 'post'
    template_name = 'blog/detail.html'


class BlogPublish(LoginRequiredMixin, CreateView):
    template_name = 'blog/publish.html'
    form_class = RegisterModelForm

    def get_success_url(self):
        last_post = Blog.objects.filter(
            owner=self.request.user).latest('publish')
        return f'/blog/detail/{last_post.id}'

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>
        {%block title%} blog {%endblock title%}
    </title>

    <link rel="Shortcut Icon" href="{%static 'blog/images/favicon.ico'%}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet"> {% block css %} {% endblock css %}

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{%url 'blog:index' %}">BLOG</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:index'%}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:list' %}">Myposts</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:publish' %}">publish</a>
                    </li>

                    {% if user.is_anonymous %}
                    <li class="nav-item">
                        <!-- {% if user.is_anonymous %} -->
                        <a class="nav-link" href="{% url 'blog:login' %}">login</a>
                        <!-- {% else %} -->
                        <!-- <a class="nav-link" href="{% url 'blog:logout' %}">{{ user }}|logout</a> -->
                        <!-- <a class="nav-link" href="/admin/password_change">|Change password</a> -->
                        <!-- {% endif %} -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:logout' %}">{{ user }}|logout</a>
                        <!-- <a class="nav-link" href="/admin/password_change">|Change password</a> -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/password_change">Change password</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Navigation -->


    <!-- Page Header -->
    {% block header %} {% endblock header %}
    <!-- Main Content -->
    {% block content %} {% endblock content %}
    <hr>

    <!-- Footer -->
    {% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <!-- <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li> -->
                        <li class="list-inline-item">
                            <a href="https://github.com/yanjl/blog_auth">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>

                        <li class="list-inline-item">
                            <span>
                                <p>{%now "Y F jS H:i" %}</p>
                            </span>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Blog Display Website 2018</p>
                </div>
            </div>
        </div>
    </footer>
    {% endblock footer %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{%static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %} {%block title%}Post{%endblock title%}

<!-- Page Header -->
{% block header%}
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>{{post.title}}</h1>

          <span class="meta">Posted on {{post.publish}}</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock header %}
<!-- Post Content -->
{% block content %}
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>{{post.body}}</p>


      </div>
    </div>
  </div>
</article>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %} {%block title%}Home{%endblock title%} {% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by WYU</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock header %}
<!-- Main Content -->

blog/templates/blog/list.html
{% extends 'blog/base.html' %} {%block title%}List{%endblock title%} {% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>{{user|title}}'s Posts</h1>
                    <p class="post-meta">Total of {{total}} Posts</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
<!-- Main Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
            <div class="post-preview">
                <a href="{% url 'blog:detail' post.id %}">
                    <h2 class="post-title">
                        {{post.title}}
                    </h2>
                </a>
                <p class="post-meta">Posted on {{post.publish}}</p>
            </div>
            <hr>
            {%empty%}
            <p>Sorry, has no posts.</p>
            {% endfor %} {%if is_paginated %}
            <div class="float-right">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number}}">上一页</a>
                    </li>
                    {% endif %} {%for c in paginator.page_range %} {%if c == page_obj.number %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{c}}">{{c}}</a>
                    </li>
                    {%else%}
                    <li class="page-item">
                        <a class="page-link" href="?page={{c}}">{{c}}</a>
                    </li>
                    {%endif%} {%endfor%} {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            {%endif%}

        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %} {%block title%} Login {%endblock title%} {% block header%}
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>Please login</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %} {% if next %} {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed, please login with an account that has
                access.</p>
            {% else %}
            <p>Please login to see this page.</p>
            {% endif %} {% endif %}

            <form role="form" name="sentMessage" id="contactForm" method="POST" action="{% url 'blog:login' %}">
                {%csrf_token%}

                <div class="form-group">

                    <table>
                        <tr>
                            <td>{{ form.username.label_tag }}</td>
                            <td>{{ form.username }}</td>
                        </tr>

                        <tr>
                            <td>{{ form.password.label_tag }}</td>
                            <td>{{ form.password }}</td>
                        </tr>
                    </table>
                </div>


                <br>
                <div class="form-group ">
                    <button type="submit " class="btn btn-primary " id="sendMessageButton ">Login</button>
                </div>
                <div class="form-group ">
                    <input type="hidden" name="next" value="{{ next }}"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/logout.html
{% extends "blog/base.html" %} {%block title%} Logout {%endblock title%} {%block header%}
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1> Logged out!</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}

blog/templates/blog/publish.html
{%extends 'blog/base.html' %} {% block title%}Publish{%endblock title%} {%block header %}
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Publish</h1>
                    <span class="subheading">Publish your post</span>
                </div>
            </div>
        </div>
    </div>
</header>
{%endblock header%} {%block content%}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% comment %}
            <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
            {% endcomment %}
            <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
            <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
            <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form role="form" name="sentMessage" id="contactForm" method="POST">
                {%csrf_token%}
                <div class="form-group">
                    {{form}}
                </div>

                <br>
                <div class="form-group ">
                    <button type="submit " class="btn btn-primary " id="sendMessageButton ">Publish</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock content%}